services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\CrudHistoryBundle\:
        resource: '../../*'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Page/'
            - '../../Kernel.php'


    whatwedo\CrudHistoryBundle\EventSubscriber\AuditTriggerSubscriber:
        tags:
            - name: 'doctrine.event_subscriber'
              priority: 500

